### PR TITLE
Adds support for using Berglas

### PR DESCRIPTION
**Pull request by madsnedergaard**
# Goal

Support using [berglas](https://github.com/GoogleCloudPlatform/berglas) for handling secrets.

## Details

Using this flag will run [berglas](https://github.com/GoogleCloudPlatform/berglas) when starting the container.

Berglas will fetch secrets from Google Secrets Manager and make them available for the app, without writing them to the image or container.

## What this does

When the `use_berglas` flag is enabled during `build` step, the following is added to the dockerfile:

```
COPY --from=us-docker.pkg.dev/berglas/berglas/berglas:latest /bin/berglas /bin/berglas

ENTRYPOINT exec /bin/berglas exec -- {normal_entrypoint_from_BUILD_file}
```

## Example of usage

```yaml
  build:
    entrypoint: yarn start
    use_berglas: true # This is the new flag - it has to be used on the build step
    tag: eu.gcr.io/PROJECT_ID/APP_NAME
    inputs:
      - index.js

  # This is an example of how the secrets can then be used in deployment with Google Cloud Run
  deploy:
    image: google/cloud-sdk:307.0.0-alpine
    commands:
      - gcloud run deploy APP_NAME
        --image eu.gcr.io/PROJECT_ID/APP_NAME
        --set-env-vars "API_KEY=sm://PROJECT_ID/your_secret_name"

```

### CODE REVIEW

**Comment by corradio** [comment]
@madsnedergaard I'm wondering if brick should become very tooling specific, or if it should become tool-agnostic.
Do you see a way to support berglas without being berglas-specific?
@skovhus I'd be curious to hear your thoughts.

To be clear I don't have a preference, but I believe we're at a crossroad and making a decision now will put on a specific path for the future.

**Comment by skovhus** [comment]
> I'm wondering if brick should become very tooling specific, or if it should become tool-agnostic.
Do you see a way to support berglas without being berglas-specific?

I do see Brick as a very internal tool, and the value of Brick is that we can quickly make adjustments that fits our needs. But I would like if we enable the products to use Brick without needing too many custom adjustment. So Tomorrow specific but tool-agnostic if possible.

In this case, I'm wondering if the user could do the following instead of adding the `use_berglas` flag?
- specify `COPY --from=us-docker.pkg.dev...` as a `command` 
- specify `ENTRYPOINT exec /bin/berglas exec -- something` as an `entrypoint` (in this case we need Brick to detect if the entrypoint is prefixed with `ENTRYPOINT` or not, as it currently prefixes the given value with `CMD` – which it shouldn't)

**Comment by madsnedergaard** [comment]
Interesting topic, thanks for pointing it out @corradio!

I generally agree with what you're both raising here and I'll change this PR to reflect it. 

(**ADDED:**)We are however making multiple steps more "advanced" in order to support this functionality, which I'm unsure if we'll need for anything else.

I'm however also slightly worried that we end up creating a tool that is very tool-agnostic, customizable and complex, as that is exactly what the other tools do - we might as well just use Bazel or something similar then :)

**EDIT:**
> In this case, I'm wondering if the user could do the following instead of adding the `use_berglas` flag?
> 
> * specify `COPY --from=us-docker.pkg.dev...` as a `command`

We prefix `commands` with `RUN`, so we would have to change that. Would it make sense to have "external inputs" or something similar?

> * specify `ENTRYPOINT exec /bin/berglas exec -- something` as an `entrypoint` (in this case we need Brick to detect if the entrypoint is prefixed with `ENTRYPOINT` or not, as it currently prefixes the given value with `CMD` – which it shouldn't)

It might be possible to actually use `CMD` instead on `ENTRYPOINT`, will test that.

**Comment by madsnedergaard** [comment]
> In this case, I'm wondering if the user could do the following instead of adding the `use_berglas` flag?
> 
> * specify `COPY --from=us-docker.pkg.dev...` as a `command`

We prefix `commands` with `RUN`, so we would have to change that. Would it make sense to have "external inputs" or something similar?

> * specify `ENTRYPOINT exec /bin/berglas exec -- something` as an `entrypoint` (in this case we need Brick to detect if the entrypoint is prefixed with `ENTRYPOINT` or not, as it currently prefixes the given value with `CMD` – which it shouldn't)

It might be possible to actually use `CMD` instead on `ENTRYPOINT`, will test that.

**Comment by skovhus** [comment]
> I'm however also slightly worried that we end up creating a tool that is very tool-agnostic, customizable and complex, as that is exactly what the other tools do - we might as well just use Bazel or something similar then

💯! Totally agree with your concern. We should keep it as simple as possible, but solve our needs. Tough balance. 🙈

In this case it is a less custom code to enable consumers total flexibility over the entry point in the Dockerfile.

Slightly off topic: Another approach, in general, would be to leave the Dockerfile to the consumer. That would slim down Brick considerably to mainly be about build orchestration and dependency tracking based on COPY/ADD commands.

**Comment by skovhus** [comment]
> We prefix commands with RUN, so we would have to change that. Would it make sense to have "external inputs" or something similar?

Damn. In that case it really [leaks](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/) that we are hiding the Dockerfile from the user. We could open a loop hole that if a command starts with `COPY` then we skip the `RUN` part – but it is also rather magical.

**Comment by madsnedergaard** [comment]
> > We prefix commands with RUN, so we would have to change that. Would it make sense to have "external inputs" or something similar?
> 
> Damn. In that case it really [leaks](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/) that we are hiding the Dockerfile from the user. We could open a loop hole that if a command starts with `COPY` then we skip the `RUN` part – but it is also rather magical.

I guess that could work, although it's very much a "we do things behind the scenes" kinda hack :)

And how about having an additional list of `external_dependencies` specifically for copying other sources? Don't know if it makes sense for other use cases, just seems more generalized and flexible imo.

**Comment by skovhus** [comment]
> And how about having an additional list of external_dependencies specifically for copying other sources? Don't know if it makes sense for other use cases, just seems more generalized and flexible imo.

Good idea. It seems like a fine and general solution for now. 👍🏻

But we would still need the hack for the entrypoint.

Let me know what makes the most sense: keep the PR as is (rather Tomorrow specific) or change it to be slightly more generic using the external_dependencies option. 

In general both options shows that we might want to rethink how the Dockerfile is generated — at some point. :)

**Comment by madsnedergaard** [comment]
> > And how about having an additional list of external_dependencies specifically for copying other sources? Don't know if it makes sense for other use cases, just seems more generalized and flexible imo.
> 
> Good idea. It seems like a fine and general solution for now. 👍🏻
> 
> But we would still need the hack for the entrypoint.

Just tested it today, and it works with `CMD` - so we won't have to do anything there.
 
> Let me know what makes the most sense: keep the PR as is (rather Tomorrow specific) or change it to be slightly more generic using the external_dependencies option.

I'm leaning towards the external_dependencies now that the first "hack" is not needed.

> In general both options shows that we might want to rethink how the Dockerfile is generated — at some point. :)

Yeah, it's probably something we should discuss at some point when you're onboard and up to speed  :)

**Comment by skovhus** [comment]
Great that `CMD` works! Then `external_dependencies` seems like a clear winner!

Consider renaming to  `external_inputs` for consistency with `inputs`. :)

**Comment by madsnedergaard** [comment]
Moved to #51 as approach was changed.

**Pull request closed without merging**
