### PR TITLE
Adds "install_requires" with required dependencies

### PR DESCRIPTION
**Pull request by dafrie**
If one currently installs via:
`pip3 install -U git+ssh://git@github.com/tmrowco/brick.git@master`
the dependencies are not automatically installed. Apparently its best practice to have entries in both `requirements.txt` (for dev purposes) and `install_requires` (for packaging) and not combine in one.

### CODE REVIEW

**Comment by corradio** [comment]
Hi @dafrie,

Thanks for the PR! Could you point me to places where it's said to be best practice to separate both?
I think in this particular case I'd prefer to centralise both as we don't need dev packages (for now). I'm afraid else we might cause troubles if we add to one place but not the other.

Olivier

**Comment by dafrie** [comment]
Yeah, I also don't like the duplication. Honestly don't have much experience on python packaging, but 
here some background:
https://packaging.python.org/discussions/install-requires-vs-requirements/
https://www.reddit.com/r/Python/comments/3uzl2a/setuppy_requirementstxt_or_a_combination/
Summary: `install_requires` for minimum dependencies, `requirements.txt` for a reproducible environment. 

Some "solutions":
https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py


- ```You can flip it around and list the dependencies in setup.py and have a single character — a dot . — in requirements.txt instead.```
- Put everything in install_requires and remove requirements.txt --> Having everything in install_requires allows to ship the package to `PyPI` (if wanted)
- Put everything in requirements.txt and reference it from `install_requires` (not recommended)

Another question is: Does `docker` (probably) and `yamllint` (probably not) belong to minimum dependencies?

**Comment by corradio** [comment]
Hi @dafrie ,

Thanks for the reference. Let's remove requirements.txt then, and move everything to `install_requires`.
docker and yamllint are indeed required

**Review by corradio — APPROVED** [review]

**Comment by corradio** [comment]
thanks!

**Pull request merged**
