### PR TITLE
Add integration test setup and examples folder

### PR DESCRIPTION
**Pull request by skovhus**
https://github.com/tmrowco/brick/issues/68

When fixing a caching issue in the promotion of images, I decided to wrap up some old integrations tests I started on a while ago. Manually testing Brick is very tedious, so a few high level integrations tests really helps here. 

We are testing on a fairly high level:
- asserting which docker images was found on the system
- asserting which docker images was built (based on the log for now)
- asserting which docker images were promoted (based on the logs for now)
- a few additional asserts on the log output from Brick

We test several scenarios here:
- build a single workspace on master
- rebuilt a single workspace on master (caching)
- rebuilt a single workspace on a new branch (promoting)
- building a workspace 
- testing a workspace

### CODE REVIEW

**Comment by corradio** [comment]
I'll let @madsnedergaard review if that's fine with you.
Thanks for cc'ing me though!

**Review by madsnedergaard — APPROVED** [review]
LGTM!

**Comment by madsnedergaard** [comment]
Started reviewing yesterday, but thought I was hitting an infinite loop when running the test since my CPU was going crazy for so long - turns out it just need more time 😄

**Comment by skovhus** [comment]
> Started reviewing yesterday, but thought I was hitting an infinite loop when running the test since my CPU was going crazy for so long - turns out it just need more time 😄

Wow! They take 40 seconds on CI... Wondering if something else was wrong 🤔

**Pull request merged**
